# Generated by Django 5.1.1 on 2024-09-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('site_src', models.URLField()),
                ('banner_img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='dday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('cate', models.CharField(choices=[('1', '율숍'), ('2', '우르'), ('3', '유피텔'), ('4', '니토필'), ('5', '카타튜링'), ('6', '기타')], max_length=1)),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='main_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_text', models.TextField()),
                ('cover_img_url', models.URLField()),
                ('main_img1', models.URLField()),
                ('main_img2', models.URLField()),
                ('main_img3', models.URLField()),
                ('main_img4', models.URLField()),
                ('main_color', models.TextField()),
                ('time_img', models.URLField()),
                ('dday_img', models.URLField()),
                ('header_img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('p', 'pair'), ('t', 'TRPG log'), ('c', 'commission')], max_length=1)),
                ('tag', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumnail', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
